### ISSUE TITLE
Trying to get this working with Unreal Engine : MT / MD mismatch?

### ISSUE THREAD

**Issue by datee** [haxiomic/haxe-c-bridge#37]
So - the haxe-c-bridge sounds really awesome. I would love to add lib or dll files built from Haxe to use in Unreal Engine.
For now i am experimenting a bit here - trying to build a .lib file (win64) to do just that.

But im stuck here with this build error in Unreal when adding the .h and .lib file from the haxe-c-bridge output: 
`mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' `

Guess there is a mismatch with MT / MD here. 
Havent found a good way to make it work yet - Unreal wont accept MT it seems and Haxe-C-Bridge / hxcpp complains when i try to set /MD. 

Any good suggestions on how to approach this?

**Comment by haxiomic** [comment]
Interesting! It would be great to get this working

What are you hxml arguments used to compile the .lib?

Do you intend for it to be a static lib or a dynamic one (or just whichever works?)

**Comment by datee** [comment]
Cool! It would be so awesome to get this to work!

After what i've learned it doesnt seem to be possible to include a .lib file thats using /MT , it needs to be /MD. 
But im not sure of how haxe-c-bridge can generate a lib using /MD.. is it possible?

I have made a little test project for you, that has the simplest setup of haxe-c-bridge and a UnrealEnigne 4.27 project set up to include the .lib file. Its basicly the same as your example but wrapped in a c++ Blueprint Library in unreal engine.
The `unreal\TestHaxeC\Source\TestHaxeC\` folder has a copy of the generated .h file thats being included in `unreal\TestHaxeC\Source\TestHaxeC\TestBPFL.cpp` (The blueprint library class).

In the file `TestHaxeC.Build.cs `in the same folder the .lib file is linked up (you need to change the path)
and the .lib file itself is in the folder `unreal\TestHaxeC\Binaries\Win64\`

https://www.dropbox.com/t/1Zfmtfe13n1GQkeD

It could ofcourse also be linked using a .dll dynamicly , but then you still need to include a .lib file in addition to the .h, right?

**Comment by haxiomic** [comment]
Thanks for this :), I'll visit this over the weekend

I guess you've tried switching between `-D dll_link` and `-D static_link`?

I expect we'll need to look into how hxcpp uses mscv to make sure we can control that switch

**Comment by datee** [comment]
Nice. 👌  Excited to see how it goes 😎

**Comment by haxiomic** [comment]
Cool, so it looks like you can add `-D ABI=-MD` and hxcpp will use that instead of -MT
https://github.com/HaxeFoundation/hxcpp/blob/master/toolchain/msvc-toolchain.xml#L15

This generated a .lib for me without error, presumably now linked as UE likes it but I haven't tested (it's a busy weekend)

Fingers crossed that works for you!

**Comment by datee** [comment]
Aha! Yey! Great success!! Thanks so much for the help with this!
Now, linking with MD im able to link the .lib file and run the haxe code in unreal !!

This is fantastic, it will open many new possibilites!
With some bindings and glue it should be possible to do a lot of things here :)

**Comment by haxiomic** [comment]
Yey, that’s awesome :D, very keen to hear what you create!

keep us posted on the haxe community forum

**Comment by datee** [comment]
Will do! 👍😎
