### ISSUE TITLE
Expose functions generated by another @:build / @:autobuild macro?

### ISSUE THREAD

**Issue by datee** [haxiomic/haxe-c-bridge#39]
Hi!
So, i have a build macro that generates some functions for me on a class 
and im trying to get this exposed to haxe-c-bridge. 

I'm getting code completion on the generated functions and looking at the source they are there too. 
But they are not being picked up and exposed in the generated .h file from haxe-c-bridge...
So would this be an issue of autobuild order problems? - i've tried several ways of doing it but its not really helping.

Any good ideas here ? :)

**Comment by haxiomic** [comment]
Hmm this is interesting, I would expect macro fields to be picked up because HaxeCBridge waits until after typing to generate fields, but it could be useful to put a trace in there and a trace in your macro to check the order

Could you create a minimal repro?

**Comment by datee** [comment]
So i checked the sequence, and the Context.onAfterTyping in HaxeCBridge runs AFTER my macros. But it doesnt pick up the functions... will try to put together a test for you.

**Comment by haxiomic** [comment]
Ahh good to hear, ty for the update :]
