### ISSUE TITLE
suggestions: can you rename  Main.h in cpp  ?

### ISSUE THREAD

**Issue by sonygod** [haxiomic/haxe-c-bridge#40]
suggestions: can you rename  Main.h in bin/cpp ?

because there is duplicate name in  bin/cpp/inlude/Main.h

<img width="347" alt="image" src="https://user-images.githubusercontent.com/748320/165663001-3b85f1a2-9a26-4188-943c-ebad5df64e1b.png">

**Comment by haxiomic** [comment]
You can set the generated lib name with -D HaxeCBridge.name=YourLibName
