### ISSUE TITLE
question: can you make another haxe-cpp-bridge?

### ISSUE THREAD

**Issue by sonygod** [haxiomic/haxe-c-bridge#41]
question: can you make another haxe-cpp-bridge?

because current hxcpp have a lots of unknow area ,I like your  haxe-c-bridge,everything seem well now .

**Comment by haxiomic** [comment]
Checkout the sample code for examples of making libs with hxcpp

https://github.com/HaxeFoundation/hxcpp/tree/master/test/extern-lib

@:nativeGen is what you want to make classes safe to use with outside C++

the thing missing that haxe c bridge adds is thread safety - haxe c bridge runs the haxe code in a separate thread

maybe this thread safety component could be separated out
